<?php
	
	$title = "Delete My Album";
	
	$this->headTitle($title);

?>

<h1> <?php echo $this->escapeHtml($title); ?> </h1>

<p>
 <a href="<?php echo $this->url('album',['action'=>'index']); ?>">View All Album</a> | <a href="<?php echo $this->url('album',['action'=>'add']); ?>">Add Album</a>
</p>

<p>
<?php	
	
$url   = $this->url('album', ['action' => 'delete', 'id' => $id]);

?>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($album->title) ?>" by
    "<?= $this->escapeHtml($album->artist) ?>"?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $album->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>
	
</p>