<?php
	
	$title = "Edit My Album";
	
	$this->headTitle($title);

?>

<h1> <?php echo $this->escapeHtml($title); ?> </h1>

<p>
 <a href="<?php echo $this->url('album',['action'=>'index']); ?>">View All Album</a> | <a href="<?php echo $this->url('album',['action'=>'add']); ?>">Add Album</a>
</p>

<?php

	$album = $form->get('title');
	$album->setAttribute('class','form-control');
	$album->setAttribute('placeholder','Album Title');
	
	
	$artist = $form->get('artist');
	$artist->setAttribute('class','form-control');
	$artist->setAttribute('placeholder','Artist');
	
	$submit=$form->get('submit');
	$submit->setAttribute('class', 'btn btn-primary');
	
	$submit->setAttribute('action',$this->url('album',[
		'action'=>'edit',
		'id'=>$id,
	]));
	
	$form->prepare();
	
	echo $this->form()->openTag($form);
	
?>

<div class="form-group">
	<?php
		echo $this->formLabel($album)." : ";
		echo $this->formElement($album);
		echo $this->formElementErrors()->render($album,['class'=>'help-block']);
	?>
</div>


<div class="form-group">
	<?php
		echo $this->formLabel($artist)." : ";
		echo $this->formElement($artist);
		echo $this->formElementErrors()->render($artist,['class'=>'help-block']);
	?>
</div>

<?php
	echo $this->formSubmit($submit);
	echo $this->formHidden($form->get('id'));
	echo $this->form()->closeTag();
?>