<?php
	
	$title = "My Album";
	
	$this->headTitle($title);

?>

<h1> <?php echo $this->escapeHtml($title); ?> </h1>

<p>
<a href="<?php echo $this->url('album',['action'=>'add']); ?>">Add New Album</a>
</p>

<table class="table table-striped table-bordered">
	<thead>
	<tr>
	<th>ID </th>
	<th>Artist </th>
	<th>Title </th>
	<th colspan="2">Process </th>
	</tr>
	</thead>
<tbody>
	<?php
		foreach($albums as $row)
		{	
			echo "<tr>";
			foreach($row as $album)
			{
				echo "<td>".$this->escapeHtml($album)."</td>";
			}
			echo "<td><a href='".$this->url('album',['action'=>'edit','id'=>$row->id])."'>Edit</a></td>";
			echo "<td><a href='".$this->url('album',['action'=>'delete','id'=>$row->id])."'>Delete</a></td>";
			echo "</tr>";
		}
	
	?>
	
</tbody>
</table>

